version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: loginexample
  
  web:
    build: .
    image: zerossb/loginexample.server:develop
    command: sh /code/scripts/start.sh
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
